services:

  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: gameuser
      POSTGRES_PASSWORD: passgame
      POSTGRES_DB: videogameexchange
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - api-network

  api1:
    build: .
    container_name: api1
    environment:
      DATABASE_URL: postgresql://gameuser:passgame@postgres:5432/videogameexchange
      CONTAINER_NAME: api1
    depends_on:
      - postgres
    networks:
      - api-network
    
  api2:
    build: .
    container_name: api2
    environment:
      DATABASE_URL: postgresql://gameuser:passgame@postgres:5432/videogameexchange
      CONTAINER_NAME: api2
    depends_on:
      - postgres
    networks:
      - api-network

  api3:
    build: .
    container_name: api3
    environment:
      DATABASE_URL: postgresql://gameuser:passgame@postgres:5432/videogameexchange
      CONTAINER_NAME: api3
    depends_on:
      - postgres
    networks:
      - api-network

  nginx:
    image: nginx:latest
    container_name: nginx-load-balancer
    ports:
      - "8080:80"  # expose port 80 inside container as 8080 on host
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
      - api3
    networks:
      - api-network

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - api-network

  email_consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    container_name: email_consumer
    depends_on:
      - kafka
    environment:
      - KAFKA_BOOTSTRAP=kafka:9092
    networks:
      - api-network

volumes:
  postgres_data:

networks:
  api-network:
    driver: bridge